name: battle_simulator
description: Not the battle of hands and fists

homepage: https://github.com/maheshmnj/flutter_create
issue_tracker: https://github.com/maheshmnj/flutter_create/issues

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.2
  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/
